import json
from pathlib import Path
from graphify.build import build_from_json
from graphify.cluster import cluster
from graphify.analyze import god_nodes, surprising_connections
from graphify.report import generate
from graphify.export import to_html

# Merge step: create empty extraction if missing
ast_path = Path('graphify-out/.graphify_ast.json')
cached_path = Path('graphify-out/.graphify_cached.json')
if not Path('graphify-out/.graphify_extract.json').exists():
    all_nodes, all_edges, all_hyperedges = [], [], []
    if ast_path.exists():
        ast = json.loads(ast_path.read_text())
        all_nodes.extend(ast.get('nodes', []))
        all_edges.extend(ast.get('edges', []))
    if cached_path.exists():
        cached = json.loads(cached_path.read_text())
        all_nodes.extend(cached.get('nodes', []))
        all_edges.extend(cached.get('edges', []))
        all_hyperedges.extend(cached.get('hyperedges', []))
    merged = {'nodes': all_nodes, 'edges': all_edges, 'hyperedges': all_hyperedges, 'input_tokens': 0, 'output_tokens': 0}
    Path('graphify-out/.graphify_extract.json').write_text(json.dumps(merged, indent=2))
    print(f'Merged: {len(all_nodes)} nodes, {len(all_edges)} edges')

# Build and cluster
extraction = json.loads(Path('graphify-out/.graphify_extract.json').read_text())
G = build_from_json(extraction)
communities = cluster(G)
gods = god_nodes(G)
surprises = surprising_connections(G, communities)

import networkx as nx
from networkx.readwrite import json_graph
graph_data = json_graph.node_link_data(G)
Path('graphify-out/graph.json').write_text(json.dumps(graph_data, indent=2))
Path('graphify-out/.graphify_analysis.json').write_text(json.dumps({
    'communities': {str(k): v for k, v in communities.items()},
    'cohesion': {},
    'god_nodes': gods,
    'surprises': surprises,
}, indent=2))
print(f'Graph: {G.number_of_nodes()} nodes, {G.number_of_edges()} edges, {len(communities)} communities')
print('God nodes:', [g['label'] for g in gods[:5]])

# Generate a simple report (graph is empty or generation failed)
report_lines = [
    '# Graphify Report\n',
    'Summary: generated by graphify pipeline on `lib/`.\n\n',
    '## God Nodes\n',
    '\n']
if gods:
    for g in gods:
        report_lines.append(f"- {g.get('label','<no-label>')} ({g.get('id')})\n")
else:
    report_lines.append('No god nodes detected.\n')
report_lines.append('\n## Surprising Connections\n\n')
if surprises:
    for s in surprises:
        report_lines.append(f"- {s}\n")
else:
    report_lines.append('No surprising connections detected.\n')
Path('graphify-out/GRAPH_REPORT.md').write_text(''.join(report_lines))
print('GRAPH_REPORT.md written')

# Try export to HTML
try:
    to_html(G, communities, 'graphify-out/graph.html')
    print('graph.html written')
except ValueError as e:
    print(f'Visualization skipped: {e}')
